name: Build signed apk

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set-up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: updateLintBaseline
      shell: bash
      run: ./gradlew updateLintBaseline

    - name: Build
      shell: bash
      run: ./gradlew assembleRelease

    - name: Upload files to Telegram
      uses: xz-dev/TelegramFileUploader@v1
      with:
        to-who: '-4267241570'
        message: 'infinity build'
        files: |
        app/build/outputs/apk/release/app-release.apk
      env:
        API_ID: ${{ secrets.TG_API_ID }}
        API_HASH: ${{ secrets.TG_API_HASH }}
        BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Infinity-${{github.sha}}
        path: app/build/outputs/apk/release/app-release.apk
        if-no-files-found: error
